name: Durlabh-CI-CD-Pipeline

on:
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install flask

    - name: Run Tests
      run: python -m unittest discover test

    - name: Build Docker image
      run: docker build -t durlabh-flask-app .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name flask_container durlabh-flask-app

    - name: Show Running Container
      run: docker ps

    - name: Stop Docker Container
      run: docker stop flask_container
